Doccano utils
d3london/bio-ext pull request #5
Opened 2024-10-20 15:11 UTC by drjzhn

(1) Restructured as monorepo for deployment / utils / individual projects. Now uses root-directory to keep code clean and allow absolute imports into project scripts.
(2) Added and refactored code for Doccano connection / project management / data load / label export
(3) Added scripts to test above in live Doccano project with synthetic BRCA dataset  
(4) Updated README

2024-10-20 16:39 UTC, lawrenceadams requested changes
I think this getting there - but I think we can do better in terms of how the project is setup:

everything in `src` should be its own distinct python project - using `root-dictionary` is a jank hack around this which will probably cause pain at a later date. With a tiny change we can change this to be a proper library (which is what you're essentially doing but in a more painful way imho!)

Otherwise looks good for the most part, I'd avoid getting people to add stuff to their shell profiles unless there's a good reason to?

2024-10-20 16:39 UTC, lawrenceadams commented on src/doccano_utils.py
> +            print(f"Failed to create project: {str(e)}")
I know this is really tempting to do, [but it's generally more harmful than not](https://realpython.com/the-most-diabolical-python-antipattern/)

Unless the library is going to handle a particular `Exception` then this is just obfuscating what is going on as the script won't die at this point - but will try to continue in a state where the project is broken. If the project cannot be created then we probably want the script to halt here.

If you wanted to do this for logging persons I'd log it or `print` and then re-raise the exception [like this](https://www.geeksforgeeks.org/python-reraise-the-last-exception-and-issue-warning/)

```suggestion
        project = self.client.create_project(
            name=name,
            project_type=project_type,
            description=description,
            guideline=guideline
        )
        self.current_project_id = project.id
        return project
```

2024-10-20 16:39 UTC, lawrenceadams commented on src/doccano_utils.py
> +            print(f"Failed to setup labels: {str(e)}")
Same again


```suggestion
        for label in labels:
            self.client.create_label_type(
                project_id=project_id,
                type='category',
                text=label
            )
```

2024-10-20 16:39 UTC, lawrenceadams commented on README.md
> +```
why are we adding these to global profiles?

also, macOS has used zsh [since Catolina](https://support.apple.com/en-us/102360) - I'd avoid using shell configs for project specific vars

2024-10-20 16:39 UTC, lawrenceadams commented on README.md
> +```
I thought only an admin persona would be setting this up? Or are these instructions just for global awareness etc?

2024-10-20 16:39 UTC, lawrenceadams commented on README.md
>  ```
I think this is getting over complicated to be honest, this is a hack to not setup project properly and will probably cause pain down the line? (IMHO)!

2024-10-20 16:39 UTC, lawrenceadams commented on projects/synthetic_brca/synthetic_brca_load.py
> +        return
Same thing as my other comment elsewhere, could do this if you want?

```suggestion
    try:
        with open(DATA_FILE, 'r') as file:
            data = json.load(file)
    except Exception as e:
        print(f"Failed to load samples.")
        raise e
```

2024-10-20 16:39 UTC, lawrenceadams commented on projects/synthetic_brca/synthetic_brca_load.py
> +}
Could be a comfy dataclass - but given this is only used to create project below is probs fine as is tbqh (and if we ever want to dataclass it in the future it would have minimal refactor requirement)

2024-10-21 10:53 UTC, drjzhn commented on .gitignore
> +deployment/load_var_ubuntu.sh
removed

2024-10-21 10:56 UTC, drjzhn commented on README.md
> +```
Yes, awareness. We'll make this repo public and this would be first time setup for an admin.

2024-10-21 10:56 UTC, drjzhn commented on README.md
>  ```
SORTED

2024-10-21 10:58 UTC, drjzhn commented on projects/synthetic_brca/synthetic_brca_load.py
> +}
Yeh sounds good. Can refactor this once we've tested pipeline in anger a bit more.

2024-10-21 11:03 UTC, drjzhn commented on deployment/.env.example
> +MLFLOW_ARTIFACT_ROOT=s3://mlflow-artifacts
Changed to ${...}

2024-10-21 11:05 UTC, drjzhn commented on src/doccano_utils.py
> +        self.server = server or 'http://localhost:8000'
Server hardcoded as the ports exposed in docker-compose are hardcoded.
Username/passwords are 'moving parts' that differ from user to user. 
Elastic server is a 'moving part' as not part of this whole environment, and may be other Elastic dbs in the future.

2024-10-21 17:01 UTC, lawrenceadams commented on .python-version
I think I accidentally added this - could we get rid of it? I dont think we need it and it'll just piss off all the python managers

2024-10-21 17:04 UTC, lawrenceadams commented on projects/.env.example
nice

2024-10-21 19:32 UTC, lawrenceadams approved these changes
🚀

2024-10-22 20:06 UTC, merged